# Generated by Django 6.0.2 on 2026-03-23 08:02

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_newslettersubscriber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookletDownloadRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('technology_name', models.CharField(max_length=100)),
                ('nda_agreed', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='agreement_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='contract_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='study',
            name='full_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='proposal_source',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='study',
            name='proposal_submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='study',
            name='sponsor_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='study',
            name='sponsor_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='study',
            name='consent_mode',
            field=models.CharField(choices=[('PAPER', 'Paper Consent'), ('ECONSENT', 'Electronic Consent (eConsent)'), ('HYBRID', 'Hybrid (Both Modes)')], default='ECONSENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='shipment_mode',
            field=models.CharField(choices=[('CLINIC', 'Clinic Delivery'), ('DTP', 'Direct-to-Patient (DTP)'), ('HYBRID', 'Hybrid (Both Modes)')], default='CLINIC', max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('PROPOSAL_UNDER_NEGOTIATION', 'Proposal Under Negotiation'), ('AGREEMENT_SIGNED', 'Agreement Signed'), ('IRB_PROTOCOL_INITIATED', 'IRB Protocol Initiated'), ('UNDER_IRB_SUBMISSION', 'Under IRB Submission / Development'), ('IRB_APPROVED', 'IRB Approved'), ('PREPARING_TO_LAUNCH', 'Preparing to Launch'), ('ACTIVE', 'Active'), ('RECRUITING', 'Recruiting'), ('RECRUITMENT_COMPLETED', 'Recruitment Completed'), ('ANALYSIS_UNDERWAY', 'Analysis Underway'), ('PROGRESS_REPORT_DRAFT', 'Progress Report Draft Created'), ('FINAL_REPORT_SENT', 'Project Report Sent to Sponsor'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('CLOSED_ARCHIVED', 'Closed / Archived')], default='RECRUITING', max_length=30),
        ),
        migrations.CreateModel(
            name='EducationMaterial',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='education_materials/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_education', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, max_length=1024, null=True, upload_to='partnership_logos/')),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_partnerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField()),
                ('journal', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('link', models.URLField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
