# Generated by Django 5.2.12 on 2026-03-24 01:33

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bookletdownloadrequest_study_agreement_signed_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyInquiry',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PROBIOTIC', 'Probiotic / Postbiotic'), ('NUTRACEUTICAL', 'Nutraceutical'), ('BOTANICAL', 'Botanical'), ('FUNCTIONAL_FOOD', 'Functional Food'), ('PHARMACEUTICAL', 'Pharmaceutical'), ('DEVICE', 'Device'), ('OTHER', 'Other')], max_length=50)),
                ('development_stage', models.CharField(choices=[('CONCEPT', 'Concept'), ('PRECLINICAL', 'Preclinical Complete'), ('READY', 'Ready for Clinical'), ('MARKETED', 'Marketed Product Seeking Data')], max_length=50)),
                ('needs', models.JSONField(default=list)),
                ('primary_focus', models.CharField(max_length=100)),
                ('timeline', models.CharField(choices=[('IMMEDIATE', 'Immediate (0–3 months)'), ('3_6_MONTHS', '3–6 months'), ('6_12_MONTHS', '6–12 months'), ('EXPLORING', 'Exploring Options')], max_length=50)),
                ('nda_preference', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('signatory_name', models.CharField(blank=True, max_length=255)),
                ('signatory_title', models.CharField(blank=True, max_length=255)),
                ('corporate_address', models.TextField(blank=True)),
                ('study_type_needed', models.JSONField(default=list)),
                ('target_population', models.TextField(blank=True)),
                ('budget_range', models.CharField(blank=True, choices=[('UNDER_100K', '<$100K'), ('100K_250K', '$100K–$250K'), ('250K_500K', '$250K–$500K'), ('OVER_500K', '$500K+'), ('DISCUSS', 'Prefer to Discuss')], max_length=50)),
                ('services_needed', models.JSONField(default=list)),
                ('project_description', models.TextField(blank=True)),
                ('supporting_files', models.FileField(blank=True, null=True, upload_to='inquiry_docs/')),
                ('status', models.CharField(choices=[('PRELIMINARY', 'Preliminary Lead'), ('NDA_REQUESTED', 'NDA Requested'), ('NDA_SENT', 'NDA Sent'), ('NDA_EXECUTED', 'NDA Executed'), ('QUALIFIED', 'Qualified Lead'), ('PROPOSAL_STAGE', 'Proposal Stage'), ('CLOSED_LOST', 'Closed / Lost')], default='PRELIMINARY', max_length=30)),
                ('routing_target', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
