# Generated by Django 5.2.12 on 2026-03-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_studyinquiry_corporate_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyinquiry',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studyinquiry',
            name='corporate_address_deprecated',
            field=models.TextField(blank=True, db_column='corporate_address', default='', null=True),
        ),
        migrations.AlterField(
            model_name='studyinquiry',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studyinquiry',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studyinquiry',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studyinquiry',
            name='street_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='studyinquiry',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
