# Generated by Django 5.2.12 on 2026-03-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_studyinquiry_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyinquiry',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
