# Generated by Django 5.2.12 on 2026-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_studyinquiry_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyinquiry',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True),
        ),
    ]
