# Generated by Django 5.2.12 on 2026-03-28 12:46

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_studyinquiry_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalConversation',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('ACTION_REQUIRED', 'Action Required'), ('RESOLVED', 'Resolved'), ('OPEN', 'Open')], default='OPEN', max_length=30)),
                ('is_flagged', models.BooleanField(default=False)),
                ('last_message_preview', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.participant')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_conversations', to='api.study')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalMessage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('tag', models.CharField(choices=[('SAFETY', 'Safety'), ('PROTOCOL', 'Protocol'), ('ELIGIBILITY', 'Eligibility'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='clinical_attachments/')),
                ('is_from_pi', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.clinicalconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
