# Generated by Django 5.2.12 on 2026-03-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_clinicalconversation_clinicalmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyinquiry',
            name='contact_mobile',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studyinquiry',
            name='contact_person_designation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studyinquiry',
            name='contact_person_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studyinquiry',
            name='discovery_call_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studyinquiry',
            name='discovery_call_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studyinquiry',
            name='discovery_call_timezone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studyinquiry',
            name='has_operational_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyinquiry',
            name='op_city',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studyinquiry',
            name='op_country',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studyinquiry',
            name='op_state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studyinquiry',
            name='op_street_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='studyinquiry',
            name='op_zip_code',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
