# Generated by Django 5.2.12 on 2026-03-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_studyinquiry_contact_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanttask',
            name='estimated_time',
            field=models.CharField(default='15 min', max_length=20),
        ),
        migrations.AddField(
            model_name='participanttask',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participanttask',
            name='timeline_group',
            field=models.CharField(default='Day 0', max_length=50),
        ),
        migrations.AddField(
            model_name='participanttask',
            name='visit_name',
            field=models.CharField(default='Visit 1 (Baseline)', max_length=100),
        ),
    ]
