# Generated by Django 5.2.12 on 2026-03-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_participanttask_estimated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='carrier',
            field=models.CharField(default='FedEx', max_length=50),
        ),
        migrations.AddField(
            model_name='kit',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='kit_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kit_photos/'),
        ),
        migrations.AddField(
            model_name='kit',
            name='packaging_photo',
            field=models.ImageField(blank=True, null=True, upload_to='packaging_photos/'),
        ),
        migrations.AddField(
            model_name='kit',
            name='shipping_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='symptom_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
