# Generated by Django 6.0.2 on 2026-03-01 19:48

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_facilityinquiry_delete_leadform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkProfile',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Leadership & Scientific Team', 'Leadership & Scientific Team'), ('Advisor', 'Advisor'), ('Clinical Collaborator', 'Clinical Collaborator'), ('Staff', 'Staff'), ('Partner', 'Partner')], max_length=50)),
                ('role', models.CharField(blank=True, help_text='Role, Title, or Specialty', max_length=200)),
                ('short_description', models.TextField(blank=True, help_text='1-line description')),
                ('full_bio', models.TextField(blank=True, help_text='Full bio (rich text optional)')),
                ('image', models.ImageField(blank=True, help_text='Headshot or Logo', null=True, upload_to='network/')),
                ('expertise_tags', models.JSONField(blank=True, default=list, help_text='Array of expertise tags or categories')),
                ('organization', models.CharField(blank=True, help_text='Organization or Affiliation', max_length=200)),
                ('external_link', models.URLField(blank=True, help_text='LinkedIn or Website URL')),
                ('display_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True, help_text='Publish or Hide this profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Network Profile',
                'verbose_name_plural': 'Network Profiles',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Advisor',
        ),
        migrations.DeleteModel(
            name='ClinicalCollaborator',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='StaffMember',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
