# Generated by Django 5.2.12 on 2026-03-30 17:22

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_kit_carrier_kit_expected_delivery_kit_kit_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='show_ae_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='study',
            name='show_dosing_log',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='show_ae_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='show_dosing_log',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='show_lab_upload',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AEReport',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('is_ongoing', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('related_to_product', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNSURE', 'Unsure')], max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ae_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ae_reports', to='api.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DosingLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dose_taken', models.BooleanField(default=True)),
                ('missed_reason', models.CharField(blank=True, max_length=255)),
                ('side_effects', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosing_logs', to='api.participant')),
            ],
            options={
                'unique_together': {('participant', 'date')},
            },
        ),
    ]
