# Generated by Django 5.2.12 on 2026-03-15 16:39

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_networkprofile_delete_advisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='study_docs/')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(help_text='JSON representation of fields and conditional logic')),
                ('is_published', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Stored answers')),
                ('is_complete', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionArm',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('regimen', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_number', models.CharField(max_length=100, unique=True)),
                ('kit_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Kit Assigned'), ('AWAITING', 'Awaiting Collection'), ('COLLECTED', 'Collected'), ('SHIPPED', 'Shipped by Participant'), ('RECEIVED', 'Received at Site'), ('MISSING', 'Missing'), ('DELAYED', 'Delayed'), ('DAMAGED', 'Damaged / Invalid')], default='ASSIGNED', max_length=30)),
                ('assignment_date', models.DateTimeField(blank=True, null=True)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_sid', models.CharField(max_length=50, unique=True, verbose_name='Participant Study ID')),
                ('status', models.CharField(choices=[('NEW', 'New Lead'), ('CONTACTED', 'Contact Attempted'), ('INTERESTED', 'Interested'), ('SCREENING', 'Prescreening in Progress'), ('ELIGIBLE', 'Eligible'), ('INELIGIBLE', 'Ineligible'), ('CONSENTED', 'Consented'), ('RANDOMIZED', 'Randomized'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='NEW', max_length=30)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyAssignment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PI', 'Principal Investigator'), ('COORDINATOR', 'Clinical Coordinator'), ('SPONSOR_ADMIN', 'Sponsor Admin'), ('SPONSOR_MANAGER', 'Study Manager'), ('SPONSOR_VIEWER', 'Sponsor Viewer')], max_length=30)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('SCREENING', 'Screening Visit'), ('BASELINE', 'Baseline Visit'), ('FOLLOW_UP', 'Follow-up Visit'), ('FINAL', 'Final Visit'), ('UNSCHEDULED', 'Unscheduled Visit'), ('ONBOARDING', 'Onboarding Call')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('actual_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('measurements', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutPageSettings',
        ),
        migrations.DeleteModel(
            name='BookletDownloadRequest',
        ),
        migrations.DeleteModel(
            name='CareerCategory',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='FacilitiesPageSettings',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='FacilityInquiry',
        ),
        migrations.DeleteModel(
            name='FacilityModule',
        ),
        migrations.DeleteModel(
            name='FacilityPillar',
        ),
        migrations.DeleteModel(
            name='HomePageSettings',
        ),
        migrations.DeleteModel(
            name='InnovationPageSettings',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.DeleteModel(
            name='NetworkProfile',
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.DeleteModel(
            name='ResearchCapability',
        ),
        migrations.RemoveField(
            model_name='sponsorinquiry',
            name='technology',
        ),
        migrations.DeleteModel(
            name='SuccessSignal',
        ),
        migrations.DeleteModel(
            name='SupportPageSettings',
        ),
        migrations.RemoveField(
            model_name='technologydocument',
            name='technology',
        ),
        migrations.DeleteModel(
            name='TrustBadge',
        ),
        migrations.AlterModelOptions(
            name='study',
            options={},
        ),
        migrations.RenameField(
            model_name='study',
            old_name='is_free_testing',
            new_name='compensation_enabled',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='is_paid',
            new_name='kit_tracking_enabled',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='is_active',
            new_name='lead_intake_enabled',
        ),
        migrations.RemoveField(
            model_name='study',
            name='benefit',
        ),
        migrations.RemoveField(
            model_name='study',
            name='compensation_range',
        ),
        migrations.RemoveField(
            model_name='study',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='study',
            name='description',
        ),
        migrations.RemoveField(
            model_name='study',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='study',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='study',
            name='location',
        ),
        migrations.RemoveField(
            model_name='study',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='study',
            name='type',
        ),
        migrations.AddField(
            model_name='study',
            name='actual_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='actual_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='actual_consented',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='actual_dropped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='actual_eligible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='actual_randomized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='actual_screened',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='design_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='study',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='irb_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='study',
            name='lab_uploads_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='launch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='study',
            name='portal_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='study',
            name='primary_indication',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='study',
            name='protocol_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Protocol ID / Internal ID'),
        ),
        migrations.AddField(
            model_name='study',
            name='scheduling_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='sponsor_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='study_type',
            field=models.CharField(choices=[('IN_PERSON', 'In-Person Clinical Trial'), ('VIRTUAL', 'Virtual Clinical Trial')], default='IN_PERSON', max_length=20),
        ),
        migrations.AddField(
            model_name='study',
            name='target_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='target_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='target_consented',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='target_eligible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='target_randomized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='target_screened',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('PROPOSAL_NEGOTIATION', 'Proposal Under Negotiation'), ('AGREEMENT_SIGNED', 'Agreement Signed'), ('IRB_INITIATED', 'IRB Protocol Initiated'), ('IRB_SUBMISSION', 'Under IRB Submission / Development'), ('IRB_APPROVED', 'IRB Approved'), ('PREPARING_LAUNCH', 'Preparing to Launch'), ('ACTIVE', 'Active'), ('RECRUITING', 'Recruiting'), ('RECRUITMENT_COMPLETED', 'Recruitment Completed'), ('ANALYSIS', 'Analysis Underway'), ('PROGRESS_REPORT', 'Progress Report Draft Created'), ('FINAL_REPORT', 'Project Report Sent to Sponsor'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed / Archived')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.study'),
        ),
        migrations.AddField(
            model_name='form',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='api.study'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form'),
        ),
        migrations.AddField(
            model_name='interventionarm',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arms', to='api.study'),
        ),
        migrations.AddField(
            model_name='kit',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='api.study'),
        ),
        migrations.AddField(
            model_name='participant',
            name='assigned_arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.interventionarm'),
        ),
        migrations.AddField(
            model_name='participant',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.study'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kit',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kits', to='api.participant'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='api.participant'),
        ),
        migrations.AddField(
            model_name='studyassignment',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.study'),
        ),
        migrations.AddField(
            model_name='studyassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.participant'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.visit'),
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='JobOpening',
        ),
        migrations.DeleteModel(
            name='SponsorInquiry',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.DeleteModel(
            name='TechnologyDocument',
        ),
        migrations.AlterUniqueTogether(
            name='studyassignment',
            unique_together={('study', 'user', 'role')},
        ),
    ]
