# Generated by Django 5.2.12 on 2026-03-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_study_show_ae_report_study_show_dosing_log_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='lab_uploads_enabled',
            new_name='show_lab_upload',
        ),
    ]
