# Generated by Django 5.2.12 on 2026-03-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_lab_uploads_enabled_study_show_lab_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='collection_guide',
            field=models.FileField(blank=True, null=True, upload_to='kit_guides/'),
        ),
        migrations.AddField(
            model_name='kit',
            name='return_label',
            field=models.FileField(blank=True, null=True, upload_to='return_labels/'),
        ),
        migrations.AddField(
            model_name='kit',
            name='tracking_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Kit Assigned'), ('PREPARING', 'Preparing for Sync'), ('SHIPPED', 'In Transit (Outbound)'), ('DELIVERED', 'Delivered at Node'), ('AWAITING', 'Awaiting Collection'), ('COLLECTING', 'Collection Active'), ('COLLECTED', 'Sample Collected'), ('RETURN_SHIPPED', 'Return Transit Active'), ('RECEIVED', 'Received at Central Lab'), ('MISSING', 'Node Signal Lost / Missing'), ('DELAYED', 'Logistics Delay'), ('DAMAGED', 'Damaged / Protocol Invalid')], default='ASSIGNED', max_length=30),
        ),
    ]
