# Generated by Django 5.2.12 on 2026-03-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_task_participanttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='consent_mode',
            field=models.CharField(choices=[('PAPER', 'Paper Consent'), ('ECONSENT', 'Electronic Consent (eConsent)')], default='ECONSENT', max_length=30),
        ),
        migrations.AddField(
            model_name='study',
            name='has_placebo_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='has_screening_log',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='study',
            name='is_double_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='shipment_mode',
            field=models.CharField(choices=[('CLINIC', 'Clinic Delivery'), ('DTP', 'Direct-to-Patient (DTP)')], default='CLINIC', max_length=30),
        ),
        migrations.AddField(
            model_name='study',
            name='trial_model',
            field=models.CharField(choices=[('RCT', 'Randomized Controlled Trial'), ('OPEN_LABEL', 'Open Label Study'), ('IHUT', 'In-Home Use Test'), ('REGISTRY', 'Patient Registry'), ('OBSERVATIONAL', 'Observational Study')], default='RCT', max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_type',
            field=models.CharField(choices=[('IN_PERSON', 'In-Person Clinical Trial'), ('VIRTUAL', 'Virtual Clinical Trial'), ('DECENTRALIZED', 'Decentralized Trial (Hybrid)')], default='IN_PERSON', max_length=20),
        ),
    ]
