# Generated by Django 5.2.12 on 2026-03-15 18:52

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_study_consent_mode_study_has_placebo_control_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Electronic Signature')),
                ('email', models.EmailField(max_length=254)),
                ('device_hash', models.CharField(blank=True, help_text='Anonymous browser fingerprint', max_length=255)),
                ('timezone_detected', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.participant')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='api.study')),
            ],
        ),
    ]
