# Generated by Django 5.2.12 on 2026-03-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_kit_collection_guide_kit_return_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='signed_consents/'),
        ),
        migrations.AddField(
            model_name='study',
            name='consent_template',
            field=models.FileField(blank=True, null=True, upload_to='consent_templates/'),
        ),
    ]
