# Generated by Django 5.2.12 on 2026-04-01 12:18

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_consent_signed_pdf_study_consent_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='consent_template',
            new_name='consent_template_file',
        ),
        migrations.RemoveField(
            model_name='consent',
            name='timezone_detected',
        ),
        migrations.AddField(
            model_name='consent',
            name='audit_trail',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consent',
            name='cc_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consent',
            name='cc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consent',
            name='cc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consent',
            name='pi_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consent',
            name='pi_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consent',
            name='pi_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyinquiry',
            name='primary_focus',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ConsentTemplate',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('require_participant_sig', models.BooleanField(default=True)),
                ('require_cc_verification', models.BooleanField(default=True)),
                ('require_pi_signoff', models.BooleanField(default=True)),
                ('require_witness', models.BooleanField(default=False)),
                ('require_lar', models.BooleanField(default=False)),
                ('require_initials_on_pages', models.BooleanField(default=False)),
                ('must_scroll_full', models.BooleanField(default=True)),
                ('must_answer_quiz', models.BooleanField(default=False)),
                ('irb_number', models.CharField(blank=True, max_length=100)),
                ('irb_approval_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='consent_templates/')),
                ('page_count', models.IntegerField(default=1)),
                ('placed_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_templates', to='api.study')),
            ],
            options={
                'ordering': ['-version'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consent',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='api.consenttemplate'),
        ),
    ]
