# Generated by Django 5.2.12 on 2026-03-15 19:27

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank Transfer'), ('STIPEND_CARD', 'Stipend Card'), ('CASH', 'Cash'), ('CHECK', 'Check')], max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='api.participant')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.visit')),
            ],
        ),
        migrations.CreateModel(
            name='DataAuditLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=100)),
                ('changes', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=100)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('lab_date', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='api.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(default='ONLINE_INTAKE', max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ATTEMPTED', 'Contact Attempted'), ('NO_ANSWER', 'No Answer'), ('NOT_INTERESTED', 'Not Interested'), ('INTERESTED', 'Interested'), ('NEEDS_INFO', 'Needs More Info'), ('PRESCREENING', 'Prescreening in Progress'), ('ELIGIBLE', 'Eligible'), ('INELIGIBLE', 'Ineligible'), ('SCHEDULED', 'Scheduled'), ('CONSENTED', 'Consented'), ('RANDOMIZED', 'Randomized'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='NEW', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='api.study')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('SMS', 'Text Message'), ('EMAIL', 'Email')], max_length=10)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], default='OUTBOUND', max_length=10)),
                ('outcome', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.participant')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lead')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionMatrix',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[], max_length=30)),
                ('capability', models.CharField(max_length=100)),
                ('is_allowed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('role', 'capability')},
            },
        ),
    ]
