# Generated by Django 5.2.12 on 2026-04-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_consent_template_study_consent_template_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('SURVEY', 'Questionnaire / Survey'), ('LOG', 'Daily Log (Symptoms/Meds)'), ('SENSOR', 'Device / Sensor Data'), ('UPLOAD', 'File Upload / Photo'), ('CONSENT', 'Informed Consent')], max_length=20),
        ),
    ]
