# Generated by Django 5.2.12 on 2026-04-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('SURVEY', 'Questionnaire / Survey'), ('LOG', 'Daily Log (Symptoms/Meds)'), ('SENSOR', 'Device / Sensor Data'), ('UPLOAD', 'File Upload / Photo'), ('CONSENT', 'Informed Consent')], default='SURVEY', max_length=20, null=True),
        ),
    ]
