# Generated by Django 5.2.12 on 2026-03-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_study_approval_status_study_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='benefit',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='study',
            name='compensation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='study',
            name='condition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='study',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='study',
            name='kits_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='study',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='study',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='study',
            name='privacy_standards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='study',
            name='remote_participation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='safety_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='study',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='study',
            name='time_commitment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='study',
            name='timeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='study',
            name='trial_format',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('RECRUITING', 'Recruiting'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='RECRUITING', max_length=30),
        ),
    ]
