# Generated by Django 5.2.12 on 2026-04-04 09:22

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_consent_timezone_detected_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='cc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consent',
            name='cc_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consent',
            name='participant_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consent',
            name='participant_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consent',
            name='pi_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consent',
            name='pi_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consenttemplate',
            name='require_initial_sections',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labresult',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('SHIPPED', 'Shipped'), ('PROCESSING', 'Processing'), ('RESULTED', 'Resulted'), ('ALERT', 'Alert')], default='RESULTED', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='assessments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='visit',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='visit',
            name='deviations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='visit',
            name='dispensing',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='visit',
            name='location',
            field=models.CharField(choices=[('Clinic', 'In-Clinic Visit'), ('Virtual', 'Telehealth / Virtual'), ('Home Visit', 'At-Home Visit')], default='Clinic', max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='pi_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='samples',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='consenttemplate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='consent_templates/'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('SCREENING', 'Screening Visit'), ('BASELINE', 'Baseline Visit'), ('FOLLOW_UP', 'Follow-up Visit'), ('FINAL', 'Final Visit'), ('UNSCHEDULED', 'Unscheduled Visit'), ('ONBOARDING', 'Onboarding Call')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('PROGRESS', 'Progress'), ('SAFETY', 'Safety'), ('FINAL', 'Final')], default='PROGRESS', max_length=20)),
                ('report_date', models.DateField()),
                ('file', models.FileField(upload_to='study_reports/')),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='api.study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyActionRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'Under Review'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_requests', to='api.participant')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_requests', to='api.study')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
