# Generated by Django 5.2.12 on 2026-03-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_study_coordinator_study_pi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmatrix',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
