# Generated by Django 5.2.12 on 2026-03-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('RECRUITING', 'Recruiting'), ('UPCOMING', 'Upcoming'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='RECRUITING', max_length=30),
        ),
    ]
