# Generated by Django 5.2.12 on 2026-04-07 05:27

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_stafftask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='eligibility_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stored results from the eligibility/screener form'),
        ),
        migrations.AddField(
            model_name='participant',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='status_notes',
            field=models.TextField(blank=True, help_text='Notes from PI/Coordinator regarding status changes'),
        ),
        migrations.AddField(
            model_name='participant',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('RECRUITING', 'Recruiting'), ('PENDING_REVIEW', 'Pending Review'), ('ELIGIBLE', 'Eligible'), ('INELIGIBLE', 'Not Eligible'), ('ENROLLED', 'Enrolled'), ('CONSENTED', 'Consented'), ('RANDOMIZED', 'Randomized'), ('ACTIVE', 'Active'), ('COMPLETED', 'Study Completed'), ('DROPPED', 'Dropped')], default='NEW', max_length=30),
        ),
        migrations.CreateModel(
            name='DailyMedicationLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('took_medicine', models.BooleanField(default=True)),
                ('time_taken', models.TimeField(blank=True, null=True)),
                ('full_dose', models.BooleanField(default=True)),
                ('dose_amount', models.CharField(blank=True, max_length=255)),
                ('reason_missed', models.TextField(blank=True)),
                ('noticed_side_effects', models.BooleanField(default=False)),
                ('side_effect_description', models.TextField(blank=True)),
                ('side_effect_start_time', models.CharField(blank=True, max_length=100)),
                ('side_effect_ongoing', models.BooleanField(default=False)),
                ('severity', models.CharField(blank=True, choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=20, null=True)),
                ('interfered_daily_activities', models.BooleanField(default=False)),
                ('sought_medical_care', models.BooleanField(default=False)),
                ('ae_additional_comments', models.TextField(blank=True)),
                ('overall_feeling', models.CharField(blank=True, choices=[('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20, null=True)),
                ('health_updates', models.TextField(blank=True)),
                ('supporting_file', models.FileField(blank=True, null=True, upload_to='daily_log_files/')),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='api.participant')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('participant', 'date')},
            },
        ),
    ]
