# Generated by Django 5.2.12 on 2026-03-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_study_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='consent_mode',
            field=models.CharField(choices=[('PAPER', 'Paper Consent'), ('ECONSENT', 'Electronic Consent (eConsent)'), ('HYBRID', 'Hybrid (Both Modes)')], default='ECONSENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='shipment_mode',
            field=models.CharField(choices=[('CLINIC', 'Clinic Delivery'), ('DTP', 'Direct-to-Patient (DTP)'), ('HYBRID', 'Hybrid (Both Modes)')], default='CLINIC', max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('RECRUITING', 'Recruiting'), ('ACTIVE', 'Active'), ('UPCOMING', 'Upcoming'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='RECRUITING', max_length=30),
        ),
    ]
