# Generated by Django 5.2.12 on 2026-04-07 06:56

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_participant_eligibility_data_participant_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_required_on_enrollment',
            field=models.BooleanField(default=False, help_text='Automatically assign this form to participants upon enrollment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('SURVEY', 'Questionnaire / Survey'), ('LOG', 'Daily Log (Symptoms/Meds)'), ('SENSOR', 'Device / Sensor Data'), ('UPLOAD', 'File Upload / Photo'), ('CONSENT', 'Informed Consent'), ('FORM_SIGNATURE', 'Form Signature Workflow')], default='SURVEY', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AssignedForm',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTICIPANT_SIGNED', 'Participant Signed'), ('COORDINATOR_SIGNED', 'Coordinator Signed'), ('COMPLETED', 'Fully Completed')], default='PENDING', max_length=30)),
                ('participant_signature', models.TextField(blank=True, null=True)),
                ('participant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator_signature', models.TextField(blank=True, null=True)),
                ('coordinator_signed_at', models.DateTimeField(blank=True, null=True)),
                ('pi_signature', models.TextField(blank=True, null=True)),
                ('pi_signed_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Stored answers from the form')),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='signed_forms/')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_assigned_forms', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_forms', to='api.participant')),
                ('pi_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_assigned_forms', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.study')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='participanttask',
            name='assigned_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.assignedform'),
        ),
    ]
