# Generated by Django 5.2.12 on 2026-04-08 13:46

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_form_is_required_on_enrollment_alter_task_task_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorOrganization',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('org_type', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='visibility',
            field=models.JSONField(blank=True, default=list, help_text='List of roles that can see this document: SPONSOR, PARTICIPANT, PI, COORDINATOR'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labresult',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='created_by_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='study',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='stage',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('PROPOSAL_UNDER_NEGOTIATION', 'Proposal Under Negotiation'), ('AGREEMENT_SIGNED', 'Agreement Signed'), ('IRB_PROTOCOL_INITIATED', 'IRB Protocol Initiated'), ('UNDER_IRB_SUBMISSION', 'Under IRB Submission / Development'), ('IRB_APPROVED', 'IRB Approved'), ('PREPARING_TO_LAUNCH', 'Preparing to Launch'), ('ACTIVE', 'Active'), ('RECRUITING', 'Recruiting'), ('RECRUITMENT_COMPLETED', 'Recruitment Completed'), ('ANALYSIS_UNDERWAY', 'Analysis Underway'), ('PROGRESS_REPORT_DRAFT', 'Progress Report Draft'), ('FINAL_REPORT_SENT', 'Final Report Sent'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('CLOSED_ARCHIVED', 'Closed / Archived')], default='DRAFT', max_length=30),
        ),
        migrations.AddField(
            model_name='study',
            name='target_subjects',
            field=models.IntegerField(default=0, verbose_name='Target Randomized Subjects'),
        ),
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('PROPOSAL_UNDER_NEGOTIATION', 'Proposal Under Negotiation'), ('AGREEMENT_SIGNED', 'Agreement Signed'), ('IRB_PROTOCOL_INITIATED', 'IRB Protocol Initiated'), ('UNDER_IRB_SUBMISSION', 'Under IRB Submission / Development'), ('IRB_APPROVED', 'IRB Approved'), ('PREPARING_TO_LAUNCH', 'Preparing to Launch'), ('ACTIVE', 'Active'), ('RECRUITING', 'Recruiting'), ('RECRUITMENT_COMPLETED', 'Recruitment Completed'), ('ANALYSIS_UNDERWAY', 'Analysis Underway'), ('PROGRESS_REPORT_DRAFT', 'Progress Report Draft'), ('FINAL_REPORT_SENT', 'Final Report Sent'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('CLOSED_ARCHIVED', 'Closed / Archived')], default='DRAFT', max_length=30),
        ),
        migrations.AddField(
            model_name='study',
            name='sponsor_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='api.sponsororganization'),
        ),
    ]
