# Generated by Django 5.2.12 on 2026-03-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_study_consent_mode_alter_study_shipment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='agreement_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='contract_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='study',
            name='proposal_source',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='study',
            name='proposal_submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='sponsor_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='study',
            name='sponsor_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('PROPOSAL_UNDER_NEGOTIATION', 'Proposal Under Negotiation'), ('AGREEMENT_SIGNED', 'Agreement Signed'), ('IRB_PROTOCOL_INITIATED', 'IRB Protocol Initiated'), ('UNDER_IRB_SUBMISSION', 'Under IRB Submission / Development'), ('IRB_APPROVED', 'IRB Approved'), ('PREPARING_TO_LAUNCH', 'Preparing to Launch'), ('ACTIVE', 'Active'), ('RECRUITING', 'Recruiting'), ('RECRUITMENT_COMPLETED', 'Recruitment Completed'), ('ANALYSIS_UNDERWAY', 'Analysis Underway'), ('PROGRESS_REPORT_DRAFT', 'Progress Report Draft Created'), ('FINAL_REPORT_SENT', 'Project Report Sent to Sponsor'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('CLOSED_ARCHIVED', 'Closed / Archived')], default='RECRUITING', max_length=30),
        ),
    ]
