# Generated by Django 5.2.12 on 2026-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_sponsororganization_document_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='uses_kit',
            field=models.BooleanField(default=False),
        ),
    ]
