# Generated by Django 5.2.12 on 2026-04-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_study_kit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='address_override',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='shipping_label',
            field=models.FileField(blank=True, null=True, upload_to='shipping_labels/'),
        ),
        migrations.AddField(
            model_name='study',
            name='kit_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='kit_dispatch_required',
            field=models.BooleanField(default=False),
        ),
    ]
