# Generated by Django 5.2.12 on 2026-04-09 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_kit_address_override_kit_shipping_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compensation',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='compensation',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_compensations', to='api.study'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.task'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='transaction_type',
            field=models.CharField(choices=[('TASK_COMPLETION', 'Task Completion'), ('VISIT_COMPLETION', 'Visit Completion'), ('STUDY_COMPLETION', 'Study Completion'), ('BONUS', 'Milestone Bonus'), ('OTHER', 'Other Incentive')], default='TASK_COMPLETION', max_length=30),
        ),
        migrations.AddField(
            model_name='study',
            name='reward_config',
            field=models.JSONField(blank=True, default=dict, help_text="Config for rewards: {'tasks': {'task_id': 10}, 'visits': {'visit_id': 50}, 'full_study': 100}"),
        ),
        migrations.AddField(
            model_name='study',
            name='reward_logic',
            field=models.CharField(choices=[('PER_TASK', 'Per Task Completion'), ('PER_VISIT', 'Per Visit Completion'), ('FULL_STUDY', 'Full Study Completion')], default='PER_TASK', max_length=20),
        ),
        migrations.AddField(
            model_name='study',
            name='reward_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('COUPONS', 'Coupons'), ('MIXED', 'Mixed (Both)')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('STIPEND_CARD', 'Stipend Card'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('COUPON', 'Coupon / Voucher')], default='CASH', max_length=30),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
