# Generated by Django 5.2.12 on 2026-04-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_compensation_created_at_compensation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='phase',
            field=models.CharField(choices=[('PHASE_0', 'Phase 0'), ('PHASE_1', 'Phase 1'), ('PHASE_1_2', 'Phase 1/2'), ('PHASE_2', 'Phase 2'), ('PHASE_2_3', 'Phase 2/3'), ('PHASE_3', 'Phase 3'), ('PHASE_4', 'Phase 4'), ('PILOT', 'Pilot Study'), ('BIOEQUIVALENCE', 'Bioequivalence')], default='PHASE_1', max_length=30),
        ),
        migrations.AlterField(
            model_name='study',
            name='trial_model',
            field=models.CharField(choices=[('RCT', 'Randomized Controlled Trial'), ('OPEN_LABEL', 'Open Label Study'), ('IHUT', 'In-Home Use Test'), ('REGISTRY', 'Patient Registry'), ('OBSERVATIONAL', 'Observational Study'), ('BIOEQUIVALENCE', 'Bioequivalence Study')], default='RCT', max_length=30),
        ),
    ]
