# Generated by Django 5.2.12 on 2026-04-10 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_study_phase_alter_study_trial_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymedicationlog',
            name='filled_by',
            field=models.CharField(choices=[('USER', 'User'), ('COORDINATOR', 'Coordinator')], default='USER', max_length=20),
        ),
        migrations.AddField(
            model_name='dailymedicationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OVERDUE', 'Overdue'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='dailymedicationlog',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailymedicationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailymedicationlog',
            name='date',
            field=models.DateField(),
        ),
    ]
