# Generated by Django 5.2.12 on 2026-04-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_dailymedicationlog_filled_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymedicationlog',
            name='filled_by',
        ),
        migrations.RemoveField(
            model_name='dailymedicationlog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dailymedicationlog',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='dailymedicationlog',
            name='user',
        ),
        migrations.AlterField(
            model_name='dailymedicationlog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='reward_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('COUPONS', 'Coupons'), ('MASTER_CARD', 'Master Card'), ('VISA_CARD', 'Visa Card'), ('WALMART_CARDS', 'Walmart Cards'), ('TARGET_CARD', 'Target Card'), ('CVS_CARD', 'CVS Card'), ('PUBLIX_CARDS', 'Publix Cards'), ('MIXED', 'Mixed (Both)')], default='CASH', max_length=20),
        ),
    ]
