# Generated by Django 5.2.12 on 2026-04-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_dailymedicationlog_filled_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='sponsor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
