# Generated by Django 5.2.12 on 2026-04-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_fix_sponsor_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='location_address',
            field=models.TextField(blank=True, help_text='Specific address or room for this visit'),
        ),
        migrations.AlterField(
            model_name='dailymedicationlog',
            name='date',
            field=models.DateField(),
        ),
    ]
