# Generated by Django 5.2.12 on 2026-04-12 04:27

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_consenttemplate_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aereport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dosinglog',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='consenttemplate',
            name='terms_content',
            field=models.TextField(blank=True, help_text='Textual terms displayed for participant review if no PDF is used or as a summary.'),
        ),
        migrations.AddField(
            model_name='study',
            name='screener_config',
            field=models.JSONField(blank=True, default=dict, help_text="Config for screener steps: {'steps': [{'id': 'STEP1', 'type': 'auto', 'editable': true}, ...]}"),
        ),
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='questionnaire_pdfs/')),
                ('json_structure', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyQuestionnaire',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('PDF', 'Full PDF'), ('STRUCTURED', 'Structured Questions')], default='STRUCTURED', max_length=20)),
                ('repeat_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=20)),
                ('repeat_count', models.IntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('relative_to_enrollment', models.BooleanField(default=False, help_text='Calculate dates relative to participant enrollment date')),
                ('window_open_time', models.TimeField(blank=True, help_text='Time of day window opens (e.g. 08:00)', null=True)),
                ('window_close_time', models.TimeField(blank=True, help_text='Time of day window closes (e.g. 20:00)', null=True)),
                ('allow_late_submission', models.BooleanField(default=True)),
                ('show_answers_to_participant', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_questionnaires', to='api.study')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questionnairetemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireScheduleInstance',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('window_open_at', models.DateTimeField(blank=True, null=True)),
                ('window_close_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('LATE', 'Late Submission'), ('MISSED', 'Missed Window'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lateness_minutes', models.IntegerField(default=0, help_text='Minutes submitted after window_close_at')),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('response_file', models.FileField(blank=True, null=True, upload_to='questionnaire_responses/')),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_questionnaires', to='api.participant')),
                ('study_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='api.studyquestionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
