# Generated by Django 5.2.12 on 2026-04-13 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_aereport_options_alter_dosinglog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnairetemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consent',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='api.participant'),
        ),
    ]
