# Generated by Django 5.2.12 on 2026-04-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_questionnairetemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='phase',
            field=models.CharField(choices=[('N/A', 'N/A'), ('PHASE_0', 'Phase 0'), ('PHASE_1', 'Phase 1'), ('PHASE_1_2', 'Phase 1/2'), ('PHASE_2', 'Phase 2'), ('PHASE_2_3', 'Phase 2/3'), ('PHASE_3', 'Phase 3'), ('PHASE_4', 'Phase 4'), ('PILOT', 'Pilot Study'), ('BIOEQUIVALENCE', 'Bioequivalence')], default='PHASE_1', max_length=30),
        ),
    ]
