# Generated by Django 5.2.12 on 2026-04-14 11:31

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_study_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationPageSettings',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Where Innovation Meets Scientific Proof', max_length=255)),
                ('hero_subtitle', models.TextField(default='Partner with MusB™ Research to design and execute rigorous research')),
                ('study_inquiry_email', models.EmailField(default='sales@musbresearch.com', max_length=254)),
                ('concept_inquiry_email', models.EmailField(default='innovation@musbresearch.com', max_length=254)),
                ('partnership_inquiry_email', models.EmailField(default='partnerships@musbresearch.com', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorInquiry',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('positioning', models.TextField()),
                ('focus_areas', models.JSONField(default=list)),
                ('icon_name', models.CharField(default='FlaskConical', max_length=100)),
                ('gradient_theme', models.CharField(default='blue-indigo', max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='study',
            name='masking_strategy',
            field=models.CharField(choices=[('NONE', 'None'), ('SINGLE_BLIND', 'Single Blind'), ('DOUBLE_BLIND', 'Double Blind'), ('TRIPLE_BLIND', 'Triple Blind'), ('QUADRUPLE_BLIND', 'Quadruple Blind')], default='NONE', max_length=30),
        ),
    ]
