# Generated by Django 5.2.12 on 2026-04-14 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_flexible_scheduling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studyquestionnaire',
            name='schedule_name',
            field=models.CharField(blank=True, help_text='Custom name for the schedule', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='location',
            field=models.CharField(default='Clinic', max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(max_length=100),
        ),
    ]
