# Generated by Django 5.2.12 on 2026-04-17 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_studyquestionnaire_schedule_name_visit_scheduled_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='signing_status',
            field=models.CharField(choices=[('PENDING', 'Pending Participant Signature'), ('PARTIALLY_SIGNED', 'Signed by Participant (Awaiting Coordinator)'), ('FULLY_SIGNED', 'Fully Executed (Signed by All)'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired / Superseded')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='studyquestionnaire',
            name='allow_participant_download',
            field=models.BooleanField(default=False, help_text='Allow participants to download their completed response as PDF'),
        ),
        migrations.AddField(
            model_name='studyquestionnaire',
            name='notify_staff_on_submission',
            field=models.BooleanField(default=True, help_text='Notify PI and Coordinator when a response is submitted'),
        ),
        migrations.AddField(
            model_name='visit',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Staff who performed/completed the visit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
