# Generated by Django 5.2.13 on 2026-04-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_consent_signing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairescheduleinstance',
            name='coordinator_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairescheduleinstance',
            name='coordinator_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairescheduleinstance',
            name='participant_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairescheduleinstance',
            name='participant_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairescheduleinstance',
            name='pi_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairescheduleinstance',
            name='pi_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairescheduleinstance',
            name='signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='signed_questionnaires/'),
        ),
    ]
