# Generated by Django 5.2.12 on 2026-04-18 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_questionnairescheduleinstance_coordinator_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 18, 8, 28, 29, 620834, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consent',
            name='signing_status',
            field=models.CharField(choices=[('PENDING', 'Pending Participant Signature'), ('PARTIALLY_SIGNED', 'Signed by Participant (Awaiting Coordinator)'), ('AWAITING_PI', 'Signed by Coordinator (Awaiting PI Signature)'), ('FULLY_SIGNED', 'Fully Executed (Signed by All)'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired / Superseded')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_sid',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Participant Study ID'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('RECRUITING', 'Recruiting'), ('PENDING_REVIEW', 'Pending Review'), ('ELIGIBLE', 'Eligible'), ('INELIGIBLE', 'Not Eligible'), ('ENROLLED', 'Enrolled'), ('CONSENTED', 'Consented'), ('RANDOMIZED', 'Randomized'), ('ACTIVE', 'Active'), ('COMPLETED', 'Study Completed'), ('DROPPED', 'Dropped')], db_index=True, default='NEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='questionnairescheduleinstance',
            name='scheduled_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='questionnairescheduleinstance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('LATE', 'Late Submission'), ('MISSED', 'Missed Window'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
