# Generated by Django 5.2.12 on 2026-04-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_news_created_at_alter_consent_signing_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at']},
        ),
    ]
