# Generated by Django 5.2.12 on 2026-04-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_event_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AddField(
            model_name='study',
            name='compensation_currency',
            field=models.CharField(blank=True, default='USD', max_length=10),
        ),
    ]
