# Generated by Django 5.2.12 on 2026-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_sid',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Participant Study ID'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('study', 'participant_sid')},
        ),
    ]
