# Generated by Django 5.2.13 on 2026-04-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_participant_participant_sid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='kit_description',
        ),
        migrations.RemoveField(
            model_name='study',
            name='kit_dispatch_required',
        ),
        migrations.RemoveField(
            model_name='study',
            name='kit_tracking_enabled',
        ),
        migrations.RemoveField(
            model_name='study',
            name='kits_info',
        ),
        migrations.RemoveField(
            model_name='study',
            name='uses_kit',
        ),
        migrations.DeleteModel(
            name='Kit',
        ),
    ]
