# Generated by Django 5.2.12 on 2026-04-21 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_study_kit_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['participant', 'scheduled_date'], name='api_visit_partici_24c9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status', 'scheduled_date'], name='api_visit_status_1790ea_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['participant', 'status'], name='api_visit_partici_4250f7_idx'),
        ),
    ]
