# Generated by Django 5.2.12 on 2026-04-21 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_visit_api_visit_partici_24c9aa_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataauditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='api_visit_partici_24c9aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='api_visit_status_1790ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='api_visit_partici_4250f7_idx',
        ),
        migrations.AddField(
            model_name='dataauditlog',
            name='details',
            field=models.TextField(blank=True, help_text='Human-readable description of the action'),
        ),
        migrations.AddField(
            model_name='participant',
            name='approval_status',
            field=models.CharField(choices=[('PENDING_INITIAL_REVIEW', 'Pending Initial Review'), ('COORDINATOR_REVIEWED', 'Reviewed by Coordinator (Pending PI)'), ('PI_REVIEWED', 'Reviewed by PI (Pending Coordinator)'), ('FULLY_APPROVED', 'Fully Approved & Enrolled'), ('REJECTED', 'Rejected / Ineligible')], default='PENDING_INITIAL_REVIEW', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='coordinator_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='coordinator_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='coordinator_signature',
            field=models.TextField(blank=True, help_text='Base64 signature of the coordinator', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='pi_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='pi_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='pi_signature',
            field=models.TextField(blank=True, help_text='Base64 signature of the PI', null=True),
        ),
        migrations.AlterField(
            model_name='dataauditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dataauditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='dataauditlog',
            name='model_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dataauditlog',
            name='record_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='dataauditlog',
            index=models.Index(fields=['model_name', 'record_id'], name='api_dataaud_model_n_05d611_idx'),
        ),
        migrations.AddIndex(
            model_name='dataauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='api_dataaud_action_984406_idx'),
        ),
    ]
