# Generated by Django 5.2.12 on 2026-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_dataauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataauditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], db_index=True, max_length=50),
        ),
    ]
