# Generated by Django 5.2.12 on 2026-04-21 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_dataauditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-scheduled_date']},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='api_notific_user_id_48bbdc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='api_notific_user_id_16328d_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftask',
            index=models.Index(fields=['user', '-created_at'], name='api_staffta_user_id_83af97_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftask',
            index=models.Index(fields=['study', '-created_at'], name='api_staffta_study_i_d31686_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['participant', '-scheduled_date'], name='api_visit_partici_cfb112_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status'], name='api_visit_status_6af862_idx'),
        ),
    ]
