# Generated by Django 5.2.12 on 2026-04-22 18:06

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_participanttask_api_partici_partici_9373a2_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='StudyKit',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_number', models.CharField(max_length=100, unique=True)),
                ('kit_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Kit Assigned'), ('PENDING', 'Pending Dispatch'), ('PREPARING', 'Preparing for Shipment'), ('SHIPPED', 'In Transit'), ('DELIVERED', 'Arrived at Site / Participant'), ('RETURN_SHIPPED', 'Return Transit Initiated'), ('RECEIVED', 'Samples Received at Lab'), ('DAMAGED', 'Damaged / Invalid')], default='ASSIGNED', max_length=30)),
                ('carrier', models.CharField(choices=[('FedEx', 'FedEx'), ('UPS', 'UPS'), ('DHL', 'DHL'), ('USPS', 'USPS'), ('Other', 'Other')], default='Other', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, help_text='Delivery address for DTP kits')),
                ('shipping_label_url', models.URLField(blank=True, null=True)),
                ('return_label_url', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kits', to='api.participant')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_kits', to='api.study')),
            ],
            options={
                'ordering': ['-last_updated'],
                'abstract': False,
            },
        ),
    ]
