# Generated by Django 5.2.12 on 2026-04-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_study_options_studykit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('ADDRESSED', 'Addressed'), ('OVERDUE', 'Overdue')], default='NEW', max_length=20),
        ),
    ]
