# Generated by Django 6.0.3 on 2026-04-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_study_options_studykit'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='participation_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
