# Generated by Django 6.0.3 on 2026-04-27 03:57

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_study_participation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('advisors', 'Advisors'), ('staff', 'Operational Staff')], default='staff', max_length=20)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('advisory_role', models.CharField(blank=True, default='', max_length=255)),
                ('dept', models.CharField(blank=True, default='', max_length=255)),
                ('expertise_area', models.CharField(blank=True, default='', max_length=255)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('expanded_bio', models.TextField(blank=True, default='')),
                ('expertise_tags', models.JSONField(blank=True, default=list)),
                ('areas_of_expertise', models.JSONField(blank=True, default=list)),
                ('affiliations', models.JSONField(blank=True, default=list)),
                ('publications', models.JSONField(blank=True, default=list)),
                ('image', models.CharField(blank=True, default='', max_length=512)),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=512)),
                ('system_role', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='study',
            name='consent_collection',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='study',
            name='has_study_kit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='medication_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='rct_design',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
