# Generated by Django 5.2.12 on 2026-04-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_stafftask_due_date_stafftask_status'),
        ('api', '0059_teammember_study_consent_collection_and_more'),
    ]

    operations = [
    ]
