# Generated by Django 6.0.3 on 2026-04-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_stafftask_due_date_stafftask_status'),
        ('api', '0059_teammember_study_consent_collection_and_more'),
    ]

    operations = [
    ]
