# Generated by Django 5.2.12 on 2026-04-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_merge_20260427_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.RemoveField(
            model_name='consent',
            name='template',
        ),
        migrations.AddField(
            model_name='consent',
            name='is_lar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consent',
            name='lar_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consent',
            name='lar_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consent',
            name='lar_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='study',
            name='consent_content',
            field=models.TextField(blank=True, help_text='Textual terms displayed for participant review'),
        ),
        migrations.AddField(
            model_name='study',
            name='require_cc_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='study',
            name='require_lar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='require_participant_sig',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='study',
            name='require_pi_signoff',
            field=models.BooleanField(default=True),
        ),
    ]
