# Generated by Django 6.0.3 on 2026-04-29 06:44

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_merge_20260427_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('advisors', 'Advisors'), ('staff', 'Operational Staff'), ('collaborators', 'Clinical Collaborators')], default='staff', max_length=20)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('advisory_role', models.CharField(blank=True, default='', max_length=255)),
                ('dept', models.CharField(blank=True, default='', max_length=255)),
                ('expertise_area', models.CharField(blank=True, default='', max_length=255)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('expanded_bio', models.TextField(blank=True, default='')),
                ('expertise_tags', models.JSONField(blank=True, default=list)),
                ('areas_of_expertise', models.JSONField(blank=True, default=list)),
                ('affiliations', models.JSONField(blank=True, default=list)),
                ('publications', models.JSONField(blank=True, default=list)),
                ('image', models.CharField(blank=True, default='', max_length=512)),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=512)),
                ('system_role', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strategic Advisor',
                'verbose_name_plural': 'Strategic Advisors',
                'db_table': 'api_advisor',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalCollaborator',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('advisors', 'Advisors'), ('staff', 'Operational Staff'), ('collaborators', 'Clinical Collaborators')], default='staff', max_length=20)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('advisory_role', models.CharField(blank=True, default='', max_length=255)),
                ('dept', models.CharField(blank=True, default='', max_length=255)),
                ('expertise_area', models.CharField(blank=True, default='', max_length=255)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('expanded_bio', models.TextField(blank=True, default='')),
                ('expertise_tags', models.JSONField(blank=True, default=list)),
                ('areas_of_expertise', models.JSONField(blank=True, default=list)),
                ('affiliations', models.JSONField(blank=True, default=list)),
                ('publications', models.JSONField(blank=True, default=list)),
                ('image', models.CharField(blank=True, default='', max_length=512)),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=512)),
                ('system_role', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinical Collaborator',
                'verbose_name_plural': 'Clinical Collaborators',
                'db_table': 'api_clinicalcollaborator',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('advisors', 'Advisors'), ('staff', 'Operational Staff'), ('collaborators', 'Clinical Collaborators')], default='staff', max_length=20)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('advisory_role', models.CharField(blank=True, default='', max_length=255)),
                ('dept', models.CharField(blank=True, default='', max_length=255)),
                ('expertise_area', models.CharField(blank=True, default='', max_length=255)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('expanded_bio', models.TextField(blank=True, default='')),
                ('expertise_tags', models.JSONField(blank=True, default=list)),
                ('areas_of_expertise', models.JSONField(blank=True, default=list)),
                ('affiliations', models.JSONField(blank=True, default=list)),
                ('publications', models.JSONField(blank=True, default=list)),
                ('image', models.CharField(blank=True, default='', max_length=512)),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=512)),
                ('system_role', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operational Staff',
                'verbose_name_plural': 'Operational Staff',
                'db_table': 'api_staffmember',
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('leadership', 'Leadership'), ('advisors', 'Advisors'), ('staff', 'Operational Staff'), ('collaborators', 'Clinical Collaborators')], default='staff', max_length=20),
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='api_teammember',
        ),
    ]
