# Generated by Django 5.2.12 on 2026-04-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_merge_20260427_1857'),
        ('api', '0061_delete_teammember_remove_consent_template_and_more'),
    ]

    operations = [
    ]
