# Generated by Django 5.2.12 on 2026-04-28 12:28

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_merge_20260428_1757'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('advisors', 'Advisors'), ('staff', 'Operational Staff')], default='staff', max_length=20)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('advisory_role', models.CharField(blank=True, default='', max_length=255)),
                ('dept', models.CharField(blank=True, default='', max_length=255)),
                ('expertise_area', models.CharField(blank=True, default='', max_length=255)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('expanded_bio', models.TextField(blank=True, default='')),
                ('expertise_tags', models.JSONField(blank=True, default=list)),
                ('areas_of_expertise', models.JSONField(blank=True, default=list)),
                ('affiliations', models.JSONField(blank=True, default=list)),
                ('publications', models.JSONField(blank=True, default=list)),
                ('image', models.CharField(blank=True, default='', max_length=512)),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=512)),
                ('system_role', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='consent_details',
            field=models.JSONField(blank=True, default=dict, help_text='Store IP, User Agent, Document Version, and Signature Type'),
        ),
        migrations.AddField(
            model_name='study',
            name='consent_pdf_template',
            field=models.FileField(blank=True, help_text='Original PDF template for overlaying signatures', null=True, upload_to='study_consents/'),
        ),
        migrations.AddField(
            model_name='study',
            name='is_blinded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='study',
            name='randomization_method',
            field=models.CharField(choices=[('SIMPLE', 'Simple Randomization'), ('BLOCK', 'Block Randomization'), ('STRATIFIED', 'Stratified Randomization')], default='SIMPLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PENDING_REVIEW', 'Pending Review'), ('ELIGIBLE', 'Eligible'), ('INELIGIBLE', 'Ineligible'), ('CONSENTED', 'Consented'), ('RANDOMIZED', 'Randomized'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped / Withdrawn')], db_index=True, default='NEW', max_length=30),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api.participant')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api.study')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PIIRevealLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields_revealed', models.JSONField(default=list)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reveal_logs', to='api.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
    ]
