# Generated by Django 5.2.12 on 2026-04-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_clinicalauditlog_delete_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='randomization_details',
            field=models.JSONField(blank=True, default=dict, help_text='Store randomization date, method, and seed if applicable'),
        ),
    ]
