# Generated by Django 5.2.12 on 2026-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_participant_randomization_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='screener_pdf_template',
            field=models.FileField(blank=True, help_text='Original PDF template for the screening form', null=True, upload_to='study_screeners/'),
        ),
    ]
