# Generated by Django 6.0.3 on 2026-04-29 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_advisor_clinicalcollaborator_staffmember_and_more'),
        ('api', '0065_participant_randomization_details'),
    ]

    operations = [
    ]
