# Generated by Django 5.2.13 on 2026-05-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_study_screener_pdf_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='eligibility_markers',
            field=models.JSONField(blank=True, default=dict, help_text='AI-driven validation markers for inclusion/exclusion'),
        ),
        migrations.AddField(
            model_name='study',
            name='exclusion_criteria',
            field=models.JSONField(blank=True, default=list, help_text='List of bullet points for exclusion'),
        ),
        migrations.AddField(
            model_name='study',
            name='inclusion_criteria',
            field=models.JSONField(blank=True, default=list, help_text='List of bullet points for inclusion'),
        ),
    ]
