# Generated by Django 6.0.3 on 2026-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_educationmaterial_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
