# Generated by Django 5.2.12 on 2026-05-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_participant_eligibility_markers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='eligibility_markers',
        ),
        migrations.RemoveField(
            model_name='study',
            name='exclusion_criteria',
        ),
        migrations.RemoveField(
            model_name='study',
            name='inclusion_criteria',
        ),
        migrations.AddField(
            model_name='compensation',
            name='card_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compensation',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnairetemplate',
            name='placed_fields',
            field=models.JSONField(blank=True, default=list, help_text='Coordinates for signatures and data overlay'),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('STIPEND_CARD', 'Stipend Card'), ('GIFT_CARD', 'Gift Card'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('COUPON', 'Coupon / Voucher')], default='CASH', max_length=30),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='transaction_type',
            field=models.CharField(choices=[('TASK_COMPLETION', 'Task Completion'), ('VISIT_COMPLETION', 'Visit Completion'), ('STUDY_COMPLETION', 'Study Completion'), ('TRAVEL_REIMBURSEMENT', 'Travel Reimbursement'), ('ADVERSE_EVENT', 'Adverse Event'), ('BONUS', 'Milestone Bonus'), ('OTHER', 'Other Incentive')], default='TASK_COMPLETION', max_length=30),
        ),
    ]
