# Generated by Django 5.2.12 on 2026-05-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_remove_participant_eligibility_markers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=10),
        ),
    ]
