# Generated by Django 6.0.3 on 2026-04-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_event_link_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_success_story',
            field=models.BooleanField(default=False),
        ),
    ]
