# Generated by Django 6.0.3 on 2026-05-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_news_is_success_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyassignment',
            name='role',
            field=models.CharField(choices=[('PI', 'Investigator'), ('COORDINATOR', 'Clinical Coordinator'), ('SPONSOR_ADMIN', 'Sponsor Admin'), ('SPONSOR_MANAGER', 'Study Manager'), ('SPONSOR_VIEWER', 'Sponsor Viewer')], max_length=30),
        ),
    ]
