# Generated by Django 5.2.12 on 2026-05-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_compensation_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='countries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
