# Generated by Django 5.2.12 on 2026-05-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_studyassignment_role'),
        ('api', '0070_study_countries'),
    ]

    operations = [
    ]
