# Generated by Django 5.2.13 on 2026-05-04 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_merge_20260503_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalauditlog',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_audit_logs', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='clinicalauditlog',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_audit_logs', to='api.study'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='api.participant'),
        ),
    ]
