# Generated by Django 5.2.12 on 2026-05-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_clinicalauditlog_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairescheduleinstance',
            name='clinical_score',
            field=models.IntegerField(blank=True, help_text='Total calculated score for this instrument', null=True),
        ),
    ]
