# Generated by Django 5.2.12 on 2026-05-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_questionnairescheduleinstance_clinical_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='content_snapshot',
            field=models.TextField(blank=True, help_text='Exact text of the consent terms at time of participant signing.'),
        ),
        migrations.AddField(
            model_name='questionnairetemplate',
            name='category',
            field=models.CharField(choices=[('SCREENER', 'Screener Form'), ('INSTRUMENT', 'Clinical Instrument / Questionnaire')], default='INSTRUMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='questionnairetemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
