# Generated by Django 5.2.13 on 2026-05-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_consent_content_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedform',
            name='completed_by',
            field=models.CharField(blank=True, choices=[('PARTICIPANT', 'Participant'), ('COORDINATOR', 'Coordinator'), ('SYSTEM', 'System Auto-generated')], help_text='Who actually filled out and submitted the data', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='questionnairescheduleinstance',
            name='completed_by',
            field=models.CharField(blank=True, choices=[('PARTICIPANT', 'Participant'), ('COORDINATOR', 'Coordinator'), ('SYSTEM', 'System Auto-generated')], help_text='Who actually filled out and submitted the data', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studyquestionnaire',
            name='timing_slot',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning (08:00 - 12:00)'), ('NOON', 'Noon (12:00 - 16:00)'), ('EVENING', 'Evening (16:00 - 20:00)'), ('NIGHT', 'Night (20:00 - 00:00)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aereport',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ae_reports', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='assignedform',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_forms', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='clinicalconversation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.participant'),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='dailymedicationlog',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_logs', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='dosinglog',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dosing_logs', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_responses', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='participanttask',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='questionnairescheduleinstance',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_questionnaires', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='api.participant'),
        ),
    ]
