# Generated by Django 5.2.12 on 2026-05-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_assignedform_completed_by_participant_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyquestionnaire',
            name='timing_slot',
        ),
        migrations.AddField(
            model_name='studyquestionnaire',
            name='window_preset',
            field=models.CharField(choices=[('MORNING', 'Morning (06:00 - 10:00)'), ('NOON', 'Noon (11:00 - 14:00)'), ('EVENING', 'Evening (17:00 - 21:00)'), ('NIGHT', 'Night (22:00 - 05:00)'), ('CUSTOM', 'Custom Times')], default='CUSTOM', max_length=20),
        ),
    ]
