# Generated by Django 5.2.12 on 2026-03-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auditlog_tokenblacklist_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
