# Generated by Django 5.2.12 on 2026-03-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_created_by_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESHED', 'Token Refreshed'), ('TOKEN_REVOKED', 'Token Revoked'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('ROLE_CHANGED', 'Role Changed'), ('ACCOUNT_CREATED', 'Account Created'), ('ACCOUNT_DISABLED', 'Account Disabled'), ('GOOGLE_LOGIN', 'Google Login'), ('RATE_LIMITED', 'Rate Limited'), ('CREDENTIALS_REISSUED', 'Credentials Reissued'), ('UPDATE_STUDY', 'Update Study'), ('DELETE_RECORD', 'Delete Record'), ('VIEW_DATA', 'View Data'), ('EXPORT_DATA', 'Export Data'), ('SYSTEM_CONFIG_CHANGE', 'System Config Change')], max_length=30),
        ),
    ]
