# Generated by Django 5.2.12 on 2026-03-19 11:26

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_facilityinquiry_news_study_approval_status_and_more'),
        ('authentication', '0007_user_zip_code_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='scope',
            field=models.CharField(default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='invitation',
            name='study_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(choices=[('musb', 'MusB'), ('onsite', 'Onsite')], default='musb', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_studies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='cv_document',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='insurance_certificate',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_licence',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('sponsor', 'Sponsor'), ('coordinator', 'Coordinator'), ('pi', 'PI'), ('team_member', 'Team Member'), ('PARTICIPANT', 'Participant')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('sponsor', 'Sponsor'), ('coordinator', 'Coordinator'), ('pi', 'PI'), ('team_member', 'Team Member'), ('PARTICIPANT', 'Participant')], default='PARTICIPANT', max_length=30),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_approvals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='api.study')),
                ('target_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
