# Generated by Django 5.2.12 on 2026-03-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_invitation_scope_invitation_study_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='scope',
            field=models.CharField(blank=True, default='ALL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='study_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='affiliation',
            field=models.CharField(blank=True, choices=[('musb', 'MusB'), ('onsite', 'Onsite')], default='musb', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_studies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='active', max_length=20, null=True),
        ),
    ]
