# Generated by Django 5.2.12 on 2026-03-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_invitation_scope_alter_invitation_study_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
