# Generated by Django 5.2.12 on 2026-04-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_auditlog_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SPONSOR', 'Sponsor'), ('COORDINATOR', 'Coordinator'), ('PI', 'PI'), ('TEAM_MEMBER', 'Team Member'), ('PARTICIPANT', 'Participant')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SPONSOR', 'Sponsor'), ('COORDINATOR', 'Coordinator'), ('PI', 'PI'), ('TEAM_MEMBER', 'Team Member'), ('PARTICIPANT', 'Participant')], default='PARTICIPANT', max_length=30),
        ),
    ]
