# Generated by Django 5.2.12 on 2026-04-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_invitation_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_screener_completed',
            field=models.BooleanField(default=False),
        ),
    ]
