# Generated by Django 5.2.12 on 2026-04-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_otp_code_remove_otp_phone_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
