# Generated by Django 6.0.3 on 2026-04-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_otp_phone_alter_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='affiliation',
            field=models.CharField(blank=True, choices=[('MUSB', 'MusB'), ('ONSITE', 'Onsite')], db_index=True, default='MUSB', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SPONSOR', 'Sponsor'), ('COORDINATOR', 'Coordinator'), ('PI', 'PI'), ('TEAM_MEMBER', 'Team Member'), ('PARTICIPANT', 'Participant')], db_index=True, default='PARTICIPANT', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20, null=True),
        ),
    ]
