# Generated by Django 5.2.12 on 2026-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_user_google_access_token_user_google_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_health_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fitbit_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fitbit_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fitbit_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_calendar_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='google_calendar_scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
