# Generated by Django 6.0.3 on 2026-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_user_apple_health_linked_user_fitbit_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mellow_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
