# Generated by Django 5.2.12 on 2026-03-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='role_summary',
            field=models.CharField(max_length=500),
        ),
    ]
