# Generated by Django 6.0.3 on 2026-05-02 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_jobposting_description_alter_jobposting_role_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-created_at']},
        ),
    ]
