# Generated by Django 6.0.3 on 2026-05-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_jobposting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='benefits',
            field=models.JSONField(default=list),
        ),
    ]
