# Generated by Django 6.0.3 on 2026-05-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_jobposting_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='apply_instructions',
            field=models.JSONField(default=list),
        ),
    ]
