# Generated by Django 6.0.3 on 2026-05-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_jobposting_apply_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
