# Generated by Django 6.0.3 on 2026-05-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_jobposting_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='about_hiring',
            field=models.JSONField(default=list),
        ),
    ]
