# Generated by Django 6.0.3 on 2026-05-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_jobposting_about_hiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='about_hiring',
            field=models.TextField(blank=True),
        ),
    ]
