# Generated by Django 6.0.3 on 2026-05-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_alter_jobposting_about_hiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Full-time Internship', 'Full-time Internship')], max_length=50),
        ),
    ]
