# Generated by Django 6.0.3 on 2026-05-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_alter_jobposting_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='responsibilities',
            field=models.JSONField(default=list),
        ),
    ]
