# Generated by Django 6.0.3 on 2026-05-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0010_jobposting_responsibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='role_summary',
            field=models.CharField(max_length=700),
        ),
    ]
