# Generated by Django 5.2.12 on 2026-04-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_submission_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
