# Generated by Django 5.2.12 on 2026-04-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_submission_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagesettings',
            name='address',
            field=models.CharField(default='Chicago, IL, USA', max_length=300),
        ),
        migrations.AddField(
            model_name='contactpagesettings',
            name='email',
            field=models.EmailField(default='info@musbresearch.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contactpagesettings',
            name='phone',
            field=models.CharField(default='+1 (773) 800-0125', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpagesettings',
            name='whatsapp',
            field=models.CharField(default='+1 (773) 800-0125', max_length=50),
        ),
    ]
