# Generated by Django 6.0.3 on 2026-04-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contactpagesettings_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='whatsapp',
        ),
    ]
