# Generated by Django 5.2.12 on 2026-05-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contactpagesettings_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='whatsapp',
        ),
    ]
