<<<<<<< HEAD
# Generated by Django 5.2.12 on 2026-05-02 09:50
=======
# Generated by Django 6.0.3 on 2026-04-29 07:48
>>>>>>> 3489bcb85d42f7741cd8cd42fda01bafd4c8e977

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contactpagesettings_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactpagesettings',
            name='whatsapp',
        ),
    ]
