# Generated by Django 6.0.3 on 2026-05-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_remove_contactpagesettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='inquiry_photos/'),
        ),
    ]
