# Heartbeat: Backend logic is healthy and connected to MongoDB.
"""
Django settings for musb_backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(override=True)

# Patch DNS resolver to fix MongoDB Atlas connection timeout
try:
    import dns.resolver
    dns.resolver.default_resolver = dns.resolver.Resolver(configure=False)
    dns.resolver.default_resolver.nameservers = ['8.8.8.8', '8.8.4.4', '1.1.1.1']
except ImportError:
    pass

# Patch Django Model hash to fix "Model instances without primary key value are unhashable"
# This is required for Django 6.x with MongoDB backends during migration/setup
import django.db.models as django_models
def _safe_model_hash(self):
    pk = getattr(self, 'pk', None)
    if pk is None:
        return id(self)
    try:
        return hash(str(pk))
    except Exception:
        return id(self)
django_models.Model.__hash__ = _safe_model_hash

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-%s_3@h)4+#%gs%)nm@xvwar%j!9e38oa_5j#m2w+0j_mblj78g')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False in production (Render) and True for local development
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')
if os.getenv('RENDER'):
    DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

# Frontend URL used for generating email links
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

ALLOWED_HOSTS = [h.strip() for h in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,musb-research-new-website-hk4k.onrender.com').split(',') if h.strip()]
if DEBUG:
    ALLOWED_HOSTS = ['*']

X_FRAME_OPTIONS = 'SAMEORIGIN'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'api',
    'contact',
    'authentication',
    'careers',
    'support',
]

AUTH_USER_MODEL = 'authentication.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.OnboardingEnforcementMiddleware',
]

ROOT_URLCONF = 'musb_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'musb_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import certifi

DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_backend',
        'HOST': os.getenv('MONGO_URI'),
        'NAME': 'musb_research',
        'CLIENT_KWARGS': {
            'tlsCAFile': certifi.where(),
            'serverSelectionTimeoutMS': 5000,
            'connectTimeoutMS': 5000,
            'socketTimeoutMS': 5000,
            'retryWrites': True,
        }
    }
}


CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,
        }
    }
}

# In local development without Redis, fallback to LocMemCache to prevent crashes
if DEBUG and not os.getenv('REDIS_URL'):
    CACHES['default'] = {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

# ─────────────────────────────────────────────────────────
#  Celery Configuration
# ─────────────────────────────────────────────────────────
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# ─────────────────────────────────────────────────────────
#  Celery Beat Schedule
# ─────────────────────────────────────────────────────────
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'check-missed-visits-every-hour': {
        'task': 'api.tasks.check_missed_visits',
        'schedule': crontab(minute=0), # Every hour
    },
}

# Silence AutoField checks for built-in Django apps (admin, auth, contenttypes)
# that hardcode AutoField. The MongoDB backend handles these at runtime.
# Silence common MongoDB and Django 6.x compatibility warnings
SILENCED_SYSTEM_CHECKS = [
    'mongodb.E001', # AutoField check
    'auth.W004',    # Permission model id check
    'fields.W342',   # JSONField default check for MongoDB
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,
        }
    },
    {
        'NAME': 'authentication.validators.ComplexPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'authentication.backends.DualAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ─────────────────────────────────────────────────────────
#  CORS & CSRF Configuration (HttpOnly Cookies)
# ─────────────────────────────────────────────────────────
CORS_ALLOW_CREDENTIALS = True

# Base allowed origins for local development
BASE_ORIGINS = [
    "http://localhost:5173", 
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://0.0.0.0:5173",
    "http://0.0.0.0:3000"
]

# ── Production origins that are ALWAYS allowed (hardcoded guarantee) ──────────
# These CANNOT be overridden by a misconfigured Render environment variable.
GUARANTEED_PROD_ORIGINS = [
    "https://musbhealth.com",
    "https://www.musbhealth.com",
    "https://musbresearchnewwebsite.vercel.app",
    "https://musb-research-new-website-hk4k.onrender.com",
]

if DEBUG:
    # When CORS_ALLOW_CREDENTIALS is True, CORS_ALLOW_ALL_ORIGINS must be False
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = BASE_ORIGINS
    CSRF_TRUSTED_ORIGINS = BASE_ORIGINS
    # Ensure local development uses the correct Vite port
    FRONTEND_URL = os.getenv('FRONTEND_URL', "http://localhost:5173")
else:
    # PRODUCTION: Merge env-var origins with hardcoded guaranteed list.
    # This means even if Render's CORS_ALLOWED_ORIGINS env var is empty or
    # outdated, musbhealth.com will ALWAYS be allowed.
    env_origins = [
        o.strip()
        for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
        if o.strip()
    ]
    CORS_ALLOWED_ORIGINS = list(set(GUARANTEED_PROD_ORIGINS + env_origins))
    CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

    # Use the primary website domain for emails/links if FRONTEND_URL environment variable is missing
    FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://musbhealth.com').strip()

# CORS_ALLOW_HEADERS = [
#     "authorization",
#     "content-type",
#     "x-csrftoken",
# ]


# Default primary key field type (MongoDB ObjectId)
DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'

# ─────────────────────────────────────────────────────────────────────────────
#  Email / SMTP Configuration
#  Reads from .env: SMTP_EMAIL, SMTP_PASSWORD, SMTP_HOST, SMTP_PORT
#  Falls back to console backend only when no credentials are configured.
# ─────────────────────────────────────────────────────────────────────────────
_smtp_email    = os.getenv('SMTP_EMAIL', '').strip()
_smtp_password = os.getenv('SMTP_PASSWORD', '').strip()
_smtp_host     = os.getenv('SMTP_HOST', 'smtp.gmail.com').strip()
_smtp_port     = int(os.getenv('SMTP_PORT', 587))

if _smtp_email and _smtp_password:
    # Real SMTP (Gmail or any provider) — used in both dev and production
    EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST          = _smtp_host
    EMAIL_PORT          = _smtp_port
    EMAIL_USE_TLS       = os.getenv('EMAIL_USE_TLS', 'True').strip().lower() in ('true', '1', 'yes')
    EMAIL_HOST_USER     = _smtp_email
    EMAIL_HOST_PASSWORD = _smtp_password
    DEFAULT_FROM_EMAIL  = f'MusB Research <{_smtp_email}>'
    SMTP_EMAIL          = _smtp_email   # expose for email_utils.py
else:
    if not DEBUG:
        # Prevent silent failures on production
        raise ValueError(
            "CRITICAL: SMTP_EMAIL and SMTP_PASSWORD environment variables are missing! "
            "Email delivery (Invitations, OTP, Resets) will FAIL. "
            "Please configure them in Render environment variables."
        )
    # Console fallback — only for local development
    EMAIL_BACKEND      = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'info@musbresearch.com'
    SMTP_EMAIL         = None

# Resend Configuration (Used as high-performance delivery option)
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '').strip()

# Production Security Settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_HTTPONLY = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1', 'yes')
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Allow Google Identity Services popups to communicate with the parent window
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'
    # Crucial for cross-domain auth (musbhealth.com -> onrender.com)
    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
else:
    # Development security
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_HTTPONLY = True
    # Ensure local development allows cross-port cookies for auth
    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'authentication.authenticate.CookieJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/minute',  # Increased limit for public API endpoints
        'user': '100000/day',   # Vastly increased for development
        'login': '100/minute',  # Scoped throttle for login endpoint only
        'refresh': '300/minute', # Scoped throttle for token refresh
        'otp_request': '30/minute', # Production-ready OTP rate limiting
        'password_reset': '30/minute', # Prevent spamming reset emails
    }
}

# Essential for HttpOnly cookies (Consolidated)
CORS_ALLOW_CREDENTIALS = True

# Suppress non-critical third-party warnings in terminal
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning, module='mongodb')
warnings.filterwarnings('ignore', category=DeprecationWarning, module='django_mongodb_backend')
warnings.filterwarnings('ignore', category=RuntimeWarning, module='django.db.models.fields')
